### ISSUE TITLE
Error on first boot

### ISSUE THREAD

**Issue by rodriguezartav** [creativetimofficial/ct-material-kit-pro-react-native#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
Download product, npm install, expo start. Then run on emulator and the app starts.

The free version worked properly.

# Current Behavior

What is the current behavior?
When the app if compiled and deployed to the emulator/device. I get the red scrren.

# Failure Information (for bugs)

Tried to register two views with the same name RNSVGPath
register
    ReactNativeViewConfigRegistry.js:76:4
<unknown>
    Path.js:28:41
loadModuleImplementation
    require.js:292:12
<unknown>
    Rect.js:2
loadModuleImplementation
    require.js:292:12
<unknown>
    index.js:1
loadModuleImplementation
    require.js:292:12
<unknown>
    Svg.js:1
loadModuleImplementation
    require.js:292:12
<unknown>
    Expo.js:649:41
loadModuleImplementation
    require.js:292:12
<unknown>
    Icon.js:2
loadModuleImplementation
    require.js:292:12
<unknown>
    index.js:4
loadModuleImplementation
    require.js:292:12
<unknown>
    App.js:4
loadModuleImplementation
    require.js:292:12
<unknown>
    AppEntry.js:2
loadModuleImplementation
    require.js:292:12
guardedLoadModule
    require.js:179:45
global code
    

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npm install
2. expo start
3. wait for app to load on device
4. Error

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Nexus 9
* Operating System: Oreo 8
* Browser and Version: 

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by palingheorghe** [comment]
Hi @rodriguezartav, 

Thank you for downloading our product! We have now solved the issue, please download the latest version of this project from our website. Contact us if you encounter any more problems.

Best wishes, 
Alin 🤙🏽
