### ISSUE TITLE
'height' and 'width' are not defined

### ISSUE THREAD

**Issue by leosuncin** [creativetimofficial/ct-material-kit-pro-react-native#10]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Detect if the running device is an iPhoneX, but the current implementation is incorrect.
Here is a working code https://gist.github.com/m-tymchyk/a7bd64ff2ee2844a4890de0aa6925fc0

# Current Behavior

On `constants/utils.js#L6` the variables `height` and `width` are undefined

```js
export const iPhoneX = () => Platform.OS === 'ios' && (height === 812 || width === 812);
```

# Failure Information (for bugs)

The only place where the function is used is on `screens/Product.js#49` and not called correctly

```
  17   │ import { iPhoneX, HeaderHeight } from "../constants/utils";

  46   │             <Image
  47   │               resizeMode="cover"
  48   │               source={{ uri: image }}
> 49   │               style={{ width, height: iPhoneX ? width + 32 : width }}
  50   │             />
```

Due is used as a variable will always be truthy because the function is not null.

```
  46   │             <Image
  47   │               resizeMode="cover"
  48   │               source={{ uri: image }}
> 49   │               style={{ width, height: iPhoneX() ? width + 32 : width }}
  50   │             />
```

The function require parenthesis after it to be called

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Unzip material-kit-pro-react-native-v1.4.0.zip
2. cd material-kit-pro-react-native-v1.4.0
3. npm install && npm install -D expo-cli@latest && expo install react-native-screens
4. Change `screens/Product.js#49`

```diff
49c49
<               style={{ width, height: iPhoneX ? width + 32 : width }}
---
>               style={{ width, height: iPhoneX() ? width + 32 : width }}
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: 
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by palingheorghe** [comment]
Hi @leosuncin ! Thank you for noticing this! We will work on implementing the fix for this issue. 

Thank you!

**Comment by palingheorghe** [comment]
This has been fixed in our last version update! Thank you for your patience!
