### ISSUE TITLE
Adding radius to a Button causes an error

### ISSUE THREAD

**Issue by davejwnz** [creativetimofficial/ct-material-kit-pro-react-native#12]
# Expected Behavior

Adding radius='2' to a Button should change a buttons borderRadius

# Current Behavior

When no radius is added no error is shown, as soon as you apply a radius on a Button an error is shown.

# Failure Information (for bugs)

In Onboarding.js adding radius='2' to a Button as a prop, causes the error

## Context

* Device: Android

**Comment by palingheorghe** [comment]
Hi @davejwnz, 

Thank you for this issue, try adding the borderRadius as a style, there's some problems regarding the Galio package and this is the easiest workaround I found. Hope this helped you! 

Thanks,
Alin
