### ISSUE TITLE
galio framework not working in expo snack

### ISSUE THREAD

**Issue by karthicware** [creativetimofficial/ct-material-kit-pro-react-native#3]
![Screenshot_20190614-172805](https://user-images.githubusercontent.com/37137867/59547948-c0767100-8f64-11e9-843d-bce710980c59.png)

**Comment by palingheorghe** [comment]
Hi @karthicware ! Thank you for your interest in our products! This is an issue related to galio-framework and not our product. For the moment being galio doesn't support Snack. 

Thanks,
Alin
