### ISSUE TITLE
Install out of the box gives error directly

### ISSUE THREAD

**Issue by ekandreas** [creativetimofficial/ct-material-kit-pro-react-native#5]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
`npm install` with no errors.

# Current Behavior
`npm install` gives error `npm ERR! Unexpected end of JSON input while parsing near '...6.0.0"},"peerDependen'`

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce
1. Download the source code
2. Unpack
3. Type `npm install`
4. Error occurs

## Failure Logs
[2019-11-20T08_24_32_263Z-debug.log](https://github.com/creativetimofficial/ct-material-kit-pro-react-native/files/3868099/2019-11-20T08_24_32_263Z-debug.log)

Please include any relevant log snippets or files here.

**Comment by palingheorghe** [comment]
Hi @ekandreas ! 

Thank you for being interested in our products! I looked over your issue and I tried to reproduce the error. Tried that on 2 different computers. As far as I can see this is a problem with your npm mirror -- it's returning incomplete files. It might be a cache error. You could try typing `npm cache clean --force` in your terminal in the `material-kit-pro-react-native` folder. 

Thanks,
Alin 🧜🏽‍♂️
