### ISSUE TITLE
Template doesn't run the browser

### ISSUE THREAD

**Issue by omniscient** [creativetimofficial/ct-material-kit-pro-react-native#6]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Would be nice to be able to run the template in Web Browser

# Current Behavior

Template doesn't seem to run out of the box in a web browser.

# Failure Information (for bugs)

## Steps to Reproduce

1. npm add react-native-web react-dom
2. npm run start
3. Press w for web

## Context

* Device: PC
* Operating System: Windows 10
* Browser and Version: Chrome latest

## Failure Logs

Failed to compile
C:/@git/cpm-mobile/src/node_modules/galio-framework/src/Toast.js 11:19
Module parse failed: Unexpected token (11:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class Toast extends Component {
>   static propTypes = {
|     children: PropTypes.node.isRequired,
|     isShow: PropTypes.bool.isRequired,

**Comment by palingheorghe** [comment]
Hi @omniscient ! 

Thank you for reaching out! This is a problem with Galio because it doesn't support React Native Web. Galio is the main UI library we're using for this project. We can't really solve this until Galio doesn't get an update regarding the React Native on Web issue.

Thanks,
Alin

**Comment by justnajm** [comment]
add this to app.json
```

	"web": {
	  "build": {
		"babel": {
		  "include": ["galio-framework"]
		}
	  }
	}
```
