### ISSUE TITLE
The template should be updated to support Not Authenticated / Authenticated routes

### ISSUE THREAD

**Issue by omniscient** [creativetimofficial/ct-material-kit-pro-react-native#7]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I find myself searching a lot after downloading the template about how to implement authentication within react native. I would have expected some sort of sample routing strategy related to authentication.

# Current Behavior

All Views are in the same router.

**Comment by palingheorghe** [comment]
Hi @omniscient ! 
Thank you for your interest in our products! Authentication is done in several possible ways so we didn't want to impose any of those ways on our customers. The `routes.js` file has nothing to do with authentication and it's only used for routing the screens in the app. Here's one article which explains one way of implementing the authentication: https://dev.to/dabit3/the-complete-react-native-guide-to-user-authentication-with-the-amplify-framework-ib2 . You could search for different ways and decide for yourself which one is better for your specific project.

Thanks,
Alin 🧜🏽‍♂️
