### ISSUE TITLE
Local expo-cli is outdated and react-native-screens is missing

### ISSUE THREAD

**Issue by leosuncin** [creativetimofficial/ct-material-kit-pro-react-native#9]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Run the app with expo: `npm start`

# Current Behavior

Fail to run

# Failure Information (for bugs)

`react-navigation-stack` depends on `react-native-screens` but is not listen in `package.json`

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Unzip material-kit-pro-react-native-v1.4.0.zip
2. cd material-kit-pro-react-native-v1.4.0
3. npm install
4. npm i -g expo-cli
5. expo start

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Android
* Operating system: Manjaro Linux 19.0.0
* Node.js version: 13.7.0
* NPM version: 6.13.6
* Expo CLI version (global): 3.13.1

## Failure Logs
<details>
<summary>Outdated expo-cli</summary>
<pre>
> rn-material-kit-pro@1.4.0 start /home/user/material-kit-pro-react-native
> cross-env REACT_EDITOR=code expo start

Starting project at /home/user/material-kit-pro-react-native
Expo DevTools is running at http://localhost:19003
Opening DevTools in the browser... (press shift-d to disable)
ConfigUtils.configFilenameAsync is not a function
TypeError: ConfigUtils.configFilenameAsync is not a function
    at _validateExpJsonAsync (/@expo/xdl@55.0.14/src/project/Doctor.js:203:40)
    at validateAsync (/@expo/xdl@55.0.14/src/project/Doctor.js:534:21)
    at startExpoServerAsync (/@expo/xdl@55.0.14/src/Project.js:1690:8)
    at Object.startAsync (/@expo/xdl@55.0.14/src/Project.js:2171:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rn-material-kit-pro@1.4.0 start: `cross-env REACT_EDITOR=code expo start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rn-material-kit-pro@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-02-17T19_05_29_844Z-debug.log
</pre>
</details>

<details>
<summary>Missing «react-native-screens» dependency</summary>
<pre>
Unable to resolve "react-native-screens" from "node_modules/react-navigation-stack/lib/module/views/StackView/StackViewCard.js"
Failed building JavaScript bundle.
</pre>
</details>

**Comment by palingheorghe** [comment]
Hi @leosuncin ! `react-navigation` got updated to v5. We are working hard to solve this issue. A small local fix you can do in order to get your app up and running is the following: 

1. download the product again
2. edit the `package.json` file and delete all `^` instances
3. `npm install`
4. `expo r -c`

The product should work as intended right now.

Thank you for your patience,
Alin

**Comment by leosuncin** [comment]
# Quick fix

Update `expo-cli` to latest version

```sh
npm install -D expo-cli@latest
```
or

```sh
yarn add -D expo-cli@latest
```

Install `react-native-screens` dependency with `expo-cli`

```sh
expo install react-native-screens
```

Now you are ready without modifying the source code.

**Comment by palingheorghe** [comment]
The app has been updated to v1.5.0 and all issues have been solved. Thanks!
